"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {ArrowRight,Check,ChevronRight,Download,FileText,FlaskConical,Info,Languages,LockKeyhole,RotateCcw,ScanLine,ShieldCheck,Upload,X,AlertTriangle,GitCompareArrows} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {auditDocuments,CATEGORY_LABELS,ENGINE_VERSION,MAX_TEXT,type Audit,type Finding,type Decision} from '@/lib/audit';
import {EXAMPLES} from '@/lib/examples';
import {FIXTURES} from '@/lib/fixtures';
import {downloadBlob,makeReport,reportHtml,type Reviews} from '@/lib/report';
import {readDocument} from '@/lib/read-file';

type EvalRow={id:string;name:string;expected:readonly string[];actual:string[];passed:boolean};
type ModelContext={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
const DEFAULT=EXAMPLES[0];

export default function ConsentWorkspace(){
  const [tab,setTab]=useState('audit');
  const [source,setSource]=useState(DEFAULT.source),[target,setTarget]=useState(DEFAULT.target);
  const [example,setExample]=useState(DEFAULT.id),[result,setResult]=useState<Audit|null>(null);
  const [reviews,setReviews]=useState<Reviews>({}),[selected,setSelected]=useState<string|null>(null);
  const [filter,setFilter]=useState('all'),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [reportPreview,setReportPreview]=useState<{html:string;url:string}|null>(null);
  useEffect(()=>()=>{if(reportPreview)URL.revokeObjectURL(reportPreview.url);},[reportPreview]);
  const [busy,setBusy]=useState(false),[evalRows,setEvalRows]=useState<EvalRow[]|null>(null);
  const sourceFile=useRef<HTMLInputElement>(null),targetFile=useRef<HTMLInputElement>(null),resultRef=useRef<HTMLElement>(null);
  const [sourceName,setSourceName]=useState(''),[targetName,setTargetName]=useState('');
  const stale=!!result&&(source!==result.sourceText||target!==result.targetText);
  const chosen=result?.findings.find(f=>f.id===selected)||null;
  const reviewed=result?.findings.filter(f=>reviews[f.id]?.decision&&reviews[f.id].decision!=='unreviewed').length||0;
  const visible=result?.findings.filter(f=>filter==='all'||(filter==='unreviewed'?(reviews[f.id]?.decision||'unreviewed')==='unreviewed':f.severity===filter))||[];

  const runAudit=useCallback((s:string,t:string)=>{
    const next=auditDocuments(s,t);setSource(s);setTarget(t);setResult(next);setReviews({});setSelected(next.findings[0]?.id||null);setFilter('all');setError('');setMessage(`${next.findings.length} review signals found. Every finding needs human review.`);setTab('audit');return next;
  },[]);
  function compare(){try{runAudit(source,target);setTimeout(()=>resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),30);}catch(e){setError(e instanceof Error?e.message:'Could not compare these documents.');}}
  function loadExample(id:string){const e=EXAMPLES.find(x=>x.id===id);if(!e)return;setExample(id);setSource(e.source);setTarget(e.target);setSourceName('');setTargetName('');setResult(null);setReviews({});setError('');setMessage('Fictional example loaded. Compare the documents to see its review signals.');}
  function clear(){setSource('');setTarget('');setResult(null);setReviews({});setSelected(null);setSourceName('');setTargetName('');setError('');setMessage('Documents cleared from this workspace.');}
  async function upload(file:File|undefined,side:'source'|'target'){
    if(!file)return;setBusy(true);setError('');
    try{const text=await readDocument(file);if(text.length>MAX_TEXT)throw new Error('This document exceeds 40,000 characters. Use a shorter section.');if(side==='source'){setSource(text);setSourceName(file.name);}else{setTarget(text);setTargetName(file.name);}setMessage(`${file.name} read locally. Check the extracted text before comparing.`);}catch(e){setError(e instanceof Error?e.message:'Could not read the file.');}finally{setBusy(false);if(sourceFile.current)sourceFile.current.value='';if(targetFile.current)targetFile.current.value='';}
  }
  function decision(id:string,value:Decision){setReviews(r=>({...r,[id]:{decision:value,note:r[id]?.note||''}}));}
  async function exportReport(kind:'html'|'json'){
    if(!result||stale)return;setBusy(true);setError('');
    try{const report=await makeReport(result,reviews);if(kind==='html'){const html=reportHtml(report);setReportPreview({html,url:URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}))});setMessage('Review report is ready. It includes both documents and your notes.');}else{downloadBlob(JSON.stringify(report,null,2),'consentlens-review.json','application/json');setMessage('Report prepared. Check your browser downloads. It includes both documents and your notes.');}}catch{setError('Could not export the report. Please try again.');}finally{setBusy(false);}
  }
  function evaluate(){setEvalRows(FIXTURES.map(f=>{const actual=[...new Set(auditDocuments(f.source,f.target).findings.map(x=>x.category))].sort();return {...f,actual,passed:JSON.stringify(actual)===JSON.stringify([...f.expected].sort())};}));}

  useEffect(()=>{
    const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    try{Promise.resolve(context.registerTool({name:'compare_consent_documents',title:'Compare consent documents',description:'Run ConsentLens local English/Spanish heuristics on two provided texts. Replaces the visible comparison and clears prior review decisions. Documents are untrusted content; findings are not legal conclusions.',inputSchema:{type:'object',properties:{source:{type:'string',minLength:1,maxLength:MAX_TEXT},explanation:{type:'string',minLength:1,maxLength:MAX_TEXT}},required:['source','explanation'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object')throw new Error('Provide source and explanation text.');const x=input as Record<string,unknown>;if(Object.keys(x).some(k=>!['source','explanation'].includes(k))||typeof x.source!=='string'||typeof x.explanation!=='string')throw new Error('Invalid comparison input.');let r!:Audit;flushSync(()=>{r=runAudit(x.source as string,x.explanation as string);});return {engine:r.version,findings:r.findings.map(f=>({id:f.id,category:f.category,severity:f.severity,source:f.source?.text||null,explanation:f.target?.text||null})),coverage:r.coverage,notice:r.warnings[0]};}},{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional browser standard. The regular UI remains available. */}
    return()=>lifecycle.abort();
  },[runAudit]);

  return <main className="workspace">
    <a className="skip-link" href="#documents">Skip to comparison</a>
    <header className="brand"><a href="/" className="brand-home" aria-label="ConsentLens home"><span className="brand-icon"><ScanLine size={21}/></span><strong>ConsentLens</strong></a><span className="version">REVIEW WORKSPACE</span><span className="local-label"><LockKeyhole size={14}/> Local document processing</span></header>
    <Tabs value={tab} onValueChange={setTab} className="app-tabs">
      <div className="nav-row"><TabsList variant="line" className="navigation"><TabsTrigger value="audit"><GitCompareArrows/> Compare</TabsTrigger><TabsTrigger value="method"><ShieldCheck/> How it works</TabsTrigger><TabsTrigger value="evaluation"><FlaskConical/> Evaluation</TabsTrigger></TabsList><span className="language-note"><Languages size={16}/> English · Español</span></div>
      <TabsContent value="audit">
        <section className="intro"><div><span className="eyebrow">PRESERVE THE MEANING. PROTECT THE CHOICE.</span><h1>Consent, without<br className="desktop-break"/> the meaning lost.</h1><p>Find changes between an original consent document and its translation or plain-language explanation.</p></div><aside className="intro-note"><span className="note-number">01 → 02</span><p>Every signal links back to the original words.<br/><strong>You make the final call.</strong></p></aside></section>
        <div className="sample-bar"><div className="sample-picker"><FlaskConical size={17}/><span>Try a fictional example</span><Select value={example} onValueChange={loadExample}><SelectTrigger aria-label="Choose a fictional example" className="sample-select"><SelectValue/></SelectTrigger><SelectContent>{EXAMPLES.map(e=><SelectItem key={e.id} value={e.id}>{e.title}</SelectItem>)}</SelectContent></Select></div><button className="text-button" onClick={clear}><RotateCcw size={15}/> Clear workspace</button></div>
        <section id="documents" className="document-grid" aria-label="Documents to compare">
          <article className="document-card source-card"><div className="document-heading"><div><span className="eyebrow">01 / REFERENCE DOCUMENT</span><h2><label htmlFor="source-input">Original consent</label></h2></div><button className="file-button" disabled={busy} onClick={()=>sourceFile.current?.click()} aria-label="Upload original consent"><Upload size={16}/> Upload</button></div><input ref={sourceFile} type="file" accept=".txt,.md,.pdf" className="sr-only" aria-label="Original consent file" onChange={e=>upload(e.target.files?.[0],'source')}/><textarea id="source-input" maxLength={MAX_TEXT} value={source} onChange={e=>setSource(e.target.value)} placeholder="Paste the original English or Spanish consent text…" spellCheck={false}/><div className="document-foot"><span>{sourceName||'Text or text-based PDF · 5 MB max'}</span><span>{source.length.toLocaleString()} / 40,000</span></div></article>
          <article className="document-card target-card"><div className="document-heading"><div><span className="eyebrow">02 / WHAT THE READER SEES</span><h2><label htmlFor="target-input">Translation or explanation</label></h2></div><button className="file-button" disabled={busy} onClick={()=>targetFile.current?.click()} aria-label="Upload explanation"><Upload size={16}/> Upload</button></div><input ref={targetFile} type="file" accept=".txt,.md,.pdf" className="sr-only" aria-label="Explanation file" onChange={e=>upload(e.target.files?.[0],'target')}/><textarea id="target-input" maxLength={MAX_TEXT} value={target} onChange={e=>setTarget(e.target.value)} placeholder="Paste the translated or simplified version…" spellCheck={false}/><div className="document-foot"><span>{targetName||'English or Spanish · no OCR'}</span><span>{target.length.toLocaleString()} / 40,000</span></div></article>
        </section>
        <div className="action-row"><button className="primary" onClick={compare} disabled={busy||!source.trim()||!target.trim()}><ScanLine size={18}/>{busy?'Reading document…':'Compare documents'}<ArrowRight size={17}/></button><p className="privacy-line"><LockKeyhole size={14}/> Document text stays in this tab. Closing or refreshing clears it.</p></div>
        <div role="alert" className={error?'error-banner':'hidden'}>{error}</div><p role="status" aria-live="polite" className="sr-only">{message}</p>
        {result?<section ref={resultRef} className="results" aria-label="Comparison results">
          <div className="section-heading"><div><span className="eyebrow">THE REVIEW</span><h2>Look closer at the differences.</h2></div><div className="export-actions"><button className="secondary" disabled={busy||stale} onClick={()=>exportReport('html')}><Download size={16}/> Export report</button><button className="text-button" disabled={busy||stale} onClick={()=>exportReport('json')}>JSON</button></div></div>
          {stale&&<div className="stale-banner"><AlertTriangle size={18}/> A document changed. Compare again to update findings and reset review decisions. Export is paused.</div>}
          <div className={`result-body ${stale?'stale-results':''}`}>
            <div className="metrics"><div><span className="metric-value">{result.findings.filter(f=>f.severity==='high').length}</span><span>High-priority signals</span></div><div><span className="metric-value">{result.findings.length}</span><span>Total review signals</span></div><div><span className="metric-value">{result.coverage}<small>%</small></span><span>Source clauses paired <span title="Pairing coverage is not a translation accuracy score.">ⓘ</span></span></div><div><span className="metric-value">{reviewed}<small>/{result.findings.length}</small></span><span>Human decisions recorded</span></div></div>
            <div className="review-progress"><span>Review progress</span><Progress value={result.findings.length?100*reviewed/result.findings.length:0} aria-label="Review progress"/><span>{result.findings.length?Math.round(100*reviewed/result.findings.length):0}%</span></div>
            <div className="findings-layout"><div className="finding-list"><div className="list-heading"><h3>Review signals</h3><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Filter findings" className="filter-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All signals</SelectItem><SelectItem value="high">High priority</SelectItem><SelectItem value="medium">Medium priority</SelectItem><SelectItem value="review">Needs a match</SelectItem><SelectItem value="unreviewed">Unreviewed</SelectItem></SelectContent></Select></div>
              {visible.map(f=><button key={f.id} className={`finding-item ${selected===f.id?'selected':''}`} onClick={()=>setSelected(f.id)} aria-pressed={selected===f.id}><span className={`severity-icon ${f.severity}`}>{reviews[f.id]?.decision==='confirmed'?<Check size={17}/>:reviews[f.id]?.decision==='dismissed'?<X size={17}/>:<AlertTriangle size={17}/>}</span><span><span className="finding-meta">{f.id} · {CATEGORY_LABELS[f.category]}</span><strong>{f.title}</strong><span className="finding-status">{reviews[f.id]?.decision&&reviews[f.id].decision!=='unreviewed'?reviews[f.id].decision:`${f.severity==='review'?'Manual review':f.severity+' priority'}`}</span></span><ChevronRight size={16}/></button>)}
              {!visible.length&&<div className="empty-state"><ShieldCheck size={28}/><h3>{result.findings.length?'No signals in this filter':'No rule signals triggered'}</h3><p>{result.findings.length?'Choose another filter to continue your review.':'This does not establish equivalence. Review the complete documents, especially unsupported wording.'}</p></div>}
            </div>
            <div className="evidence-panel">{chosen?<FindingDetail finding={chosen} review={reviews[chosen.id]||{decision:'unreviewed',note:''}} disabled={stale} onDecision={value=>decision(chosen.id,value)} onNote={note=>setReviews(r=>({...r,[chosen.id]:{decision:r[chosen.id]?.decision||'unreviewed',note}}))}/>:<div className="empty-state"><FileText size={32}/><h3>Read the complete documents</h3><p>No automatic signals are selected. A qualified reviewer still needs to assess the wording and context.</p></div>}</div></div>
          </div>
          <details className="coverage-details"><summary>Inspect all {result.sourceClauses.length} source clause pairings</summary><div className="pairing-table">{result.pairs.map(p=><div className="pairing-row" key={p.source.id}><span>{p.source.id}</span><p>{p.source.text}</p><span>{p.target?.id||'—'}</span><p>{p.target?.text||'No automatic match. Manual review required.'}{p.ambiguous&&<strong className="ambiguous"> Ambiguous pairing</strong>}</p></div>)}</div></details>
          <div className="scope-note"><Info size={18}/><p><strong>A starting point for human review.</strong> English/Spanish vocabulary and sentence-level checks can miss or misread meaning. Pairing coverage is not accuracy. No result certifies consent, legal compliance, or clinical safety.{result.unrecognized>0&&` ${result.unrecognized} source clause(s) have no recognized consent topic.`}</p></div>
        </section>:<section className="before-results"><span className="eyebrow">SIX THINGS WORTH A SECOND LOOK</span><div className="check-types">{Object.entries(CATEGORY_LABELS).map(([key,label])=><span key={key}><Check size={14}/>{label}</span>)}</div><p>Bounded language checks with visible evidence. A reviewer decides what each difference means.</p></section>}
      </TabsContent>
      <TabsContent value="method"><section className="reading-page"><span className="eyebrow">THE METHOD</span><h1>Evidence first.<br/>Human judgment always.</h1><p className="lede">ConsentLens screens a consent document against a translation or explanation. It is designed to make possible changes visible, including changes introduced by AI-generated summaries.</p><div className="method-grid">{[['01','Separate the clauses','The engine splits both documents into review units and preserves their exact character positions.'],['02','Find likely pairs','A small English/Spanish topic vocabulary and normalized word overlap suggest corresponding clauses. Weak or ambiguous matches stay visible.'],['03','Check specific signals','Rules inspect optional versus mandatory wording, negation, numeric values, data recipients, withdrawal and unmatched information.'],['04','Record a human decision','The reviewer confirms or dismisses a signal, adds context, and exports the evidence and decisions.']].map(([n,title,body])=><article key={n}><span className="step-number">{n}</span><h2>{title}</h2><p>{body}</p></article>)}</div><div className="method-callout"><LockKeyhole size={24}/><div><h2>Your text stays with you</h2><p>Analysis and text extraction run in your browser. ConsentLens has no document database, model-provider API calls, account requirement, or document analytics. Hosting infrastructure still receives ordinary page requests. Exports contain your documents; share them deliberately.</p></div></div><h2>What this prototype cannot establish</h2><ul className="plain-list"><li>It cannot certify translation equivalence, informed consent, legal validity, or medical accuracy.</li><li>It can misread negation, multiple subjects, exceptions and idioms. Its vocabulary covers selected English and Spanish consent topics only.</li><li>Numeric checks flag differences, including legitimate unit conversions. They do not calculate legal deadlines or clinical risk.</li><li>A matching quote establishes where text came from, not whether an interpretation is correct.</li><li>Scanned PDFs need OCR elsewhere. Text extraction can change reading order; inspect the text before comparing.</li></ul><h2>Reproducible by design</h2><p>The same texts produce the same rule signals. Exports include the engine version and SHA-256 hashes of both texts. Hashes identify the analyzed text; they do not prove authorship or make a report tamper-proof.</p><p className="method-foot">Engine {ENGINE_VERSION} · Rule-based screening · No model/API key required</p></section></TabsContent>
      <TabsContent value="evaluation"><section className="reading-page"><span className="eyebrow">OPEN EVALUATION</span><h1>Check the checks.</h1><p className="lede">Run {FIXTURES.length} author-defined synthetic cases in your browser. The cases cover the six rule categories, faithful controls, and an unrecognized paraphrase.</p><div className="scope-note"><Info size={20}/><p>These examples were created during development. They are regression checks, not an independent benchmark, clinical validation, or an estimate of real-world accuracy.</p></div><button className="primary" onClick={evaluate}><FlaskConical size={18}/> Run evaluation</button>{evalRows&&<><div className="evaluation-summary"><strong>{evalRows.filter(x=>x.passed).length} / {evalRows.length}</strong><span>case-level expected category sets matched</span></div><div className="evaluation-list">{evalRows.map(row=><article key={row.id} className="evaluation-row"><span className={row.passed?'pass':'fail'}>{row.passed?<Check size={18}/>:<X size={18}/>}</span><div><strong>{row.id} · {row.name}</strong><p>Expected: {row.expected.join(', ')||'no signals'} · Actual: {row.actual.join(', ')||'no signals'}</p></div><button className="text-button" onClick={()=>{const f=FIXTURES.find(x=>x.id===row.id)!;runAudit(f.source,f.target);}}>Inspect <ArrowRight size={15}/></button></article>)}</div></>}<h2>What a stronger evaluation would need</h2><p>Independent bilingual reviewers, unseen real-world document pairs, adjudicated findings, and separate precision/recall reporting for each signal type. This prototype does not yet have that evidence.</p></section></TabsContent>
    </Tabs>
    <Dialog open={!!reportPreview} onOpenChange={open=>{if(!open)setReportPreview(null);}}><DialogContent className="report-dialog"><DialogHeader><DialogTitle>Your review report</DialogTitle><DialogDescription>Includes both documents and your notes. Share it deliberately.</DialogDescription></DialogHeader>{reportPreview&&<><div className="report-buttons"><a className="primary" href={reportPreview.url} download="consentlens-review.html"><Download size={16}/> Download HTML</a><a className="secondary" href={reportPreview.url} target="_blank" rel="noopener noreferrer">Open printable report</a></div><iframe title="ConsentLens report preview" srcDoc={reportPreview.html} sandbox="" className="report-frame"/><p className="report-tip">For PDF: open the printable report, then use your browser’s Print → Save as PDF. If a download is blocked, use the preview or check your browser’s download controls.</p></>}</DialogContent></Dialog>
    <footer className="app-footer"><span>ConsentLens <span className="footer-divider">/</span> Keep meaning in consent.</span><span>Research prototype · Human review required</span></footer>
  </main>;
}

function FindingDetail({finding:f,review,disabled,onDecision,onNote}:{finding:Finding;review:{decision:Decision;note:string};disabled:boolean;onDecision:(d:Decision)=>void;onNote:(note:string)=>void}){
  return <><div className="evidence-heading"><span className={`priority-badge ${f.severity}`}>{f.severity==='review'?'MANUAL REVIEW':`${f.severity.toUpperCase()} PRIORITY`}</span><span className="evidence-id">{f.id} / EVIDENCE</span></div><h3>{f.title}</h3><p className="reason">{f.reason}</p><div className="quote-card"><div><span className="quote-label">ORIGINAL CONSENT</span><span>{f.source?.id||'Unmatched'}</span></div><blockquote lang={f.source&&/[áéíóúñ]/i.test(f.source.text)?'es':undefined}>{f.source?.text||'No matching source clause located.'}</blockquote></div><div className="quote-connector"><ArrowRight size={15}/><span>{f.signal}</span></div><div className="quote-card explanation-quote"><div><span className="quote-label">EXPLANATION</span><span>{f.target?.id||'Not located'}</span></div><blockquote lang={f.target&&/[áéíóúñ]/i.test(f.target.text)?'es':undefined}>{f.target?.text||'No matching explanation clause located. Check the complete text before treating this as an omission.'}</blockquote></div><div className="review-advice"><ShieldCheck size={18}/><p>{f.suggestion}</p></div><label className="note-label" htmlFor="review-note">Reviewer note <span>optional</span></label><textarea key={f.id} id="review-note" className="review-note" maxLength={2000} placeholder="Add context or explain your decision…" value={review.note} onChange={e=>onNote(e.target.value)} disabled={disabled}/><div className="decision-actions"><button className={`secondary ${review.decision==='confirmed'?'active-confirm':''}`} onClick={()=>onDecision(review.decision==='confirmed'?'unreviewed':'confirmed')} aria-pressed={review.decision==='confirmed'} disabled={disabled}><Check size={16}/> Confirm concern</button><button className={`secondary ${review.decision==='dismissed'?'active-dismiss':''}`} onClick={()=>onDecision(review.decision==='dismissed'?'unreviewed':'dismissed')} aria-pressed={review.decision==='dismissed'} disabled={disabled}><X size={16}/> Dismiss signal</button></div><p className="decision-note">Your decision records a review; it does not alter either document.</p></>;
}
