import type {Audit,Decision} from './audit.ts';
import {CATEGORY_LABELS,sha256} from './audit.ts';
export type Review={decision:Decision;note:string};
export type Reviews=Record<string,Review>;
export const escapeHtml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function makeReport(audit:Audit,reviews:Reviews){return {format:'consentlens-review-v1',generatedAt:new Date().toISOString(),engineVersion:audit.version,sourceSha256:await sha256(audit.sourceText),explanationSha256:await sha256(audit.targetText),notice:'Heuristic screening only. Not legal or clinical advice, proof of equivalence, or a certification of consent. Hashes identify text, not its truth or authorship.',audit,review:reviews};}
export type Report=Awaited<ReturnType<typeof makeReport>>;
export function reportHtml(report:Report){const e=escapeHtml,a=report.audit;return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ConsentLens review report</title><style>body{font:16px/1.6 Arial,sans-serif;max-width:1000px;margin:40px auto;padding:0 24px;color:#17243b}h1{font:36px Georgia,serif;color:#173dca}h2{margin-top:32px}article{border:1px solid #ccd6e6;border-left:4px solid #173dca;border-radius:6px;margin:20px 0;padding:20px;break-inside:avoid}blockquote{white-space:pre-wrap;margin:12px 0;padding:12px;background:#f2f5fa}small,footer{color:#526278;overflow-wrap:anywhere}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}.notice{background:#eef2ff;padding:16px}pre{white-space:pre-wrap;font:inherit}button{padding:10px 16px;cursor:pointer}@media print{button{display:none}body{margin:0;max-width:none}h2{break-after:avoid}}@media(max-width:650px){.pair{grid-template-columns:1fr}}</style></head><body><h1>ConsentLens</h1><p>Consent comparison &amp; reviewer record</p><p class="notice">${e(report.notice)}</p><p>${a.findings.length} review signals · ${a.coverage}% source clauses paired · ${Object.values(report.review).filter(r=>r.decision!=='unreviewed').length} decisions recorded</p><small>Created ${e(report.generatedAt)} · Engine ${e(report.engineVersion)}</small><h2>Review findings</h2>${a.findings.map(f=>{const r=report.review[f.id]||{decision:'unreviewed',note:''};return `<article><small>${e(f.id)} · ${e(CATEGORY_LABELS[f.category])} · ${e(f.severity)} priority</small><h3>${e(f.title)}</h3><p>${e(f.reason)}</p><div class="pair"><section><strong>Original ${e(f.source?.id||'')}</strong><blockquote>${e(f.source?.text||'No source match located.')}</blockquote></section><section><strong>Explanation ${e(f.target?.id||'')}</strong><blockquote>${e(f.target?.text||'No explanation match located.')}</blockquote></section></div><p><strong>Review decision:</strong> ${e(r.decision)}</p>${r.note?`<p><strong>Reviewer note:</strong> ${e(r.note)}</p>`:''}</article>`}).join('')||'<p>No signals triggered in this screening. Review all clauses manually.</p>'}<h2>Complete documents</h2><div class="pair"><section><h3>Original consent</h3><pre>${e(a.sourceText)}</pre></section><section><h3>Explanation</h3><pre>${e(a.targetText)}</pre></section></div><h2>Scope and limitations</h2><ul>${a.warnings.map(w=>`<li>${e(w)}</li>`).join('')}</ul><footer><p>Source SHA-256: ${e(report.sourceSha256)}<br>Explanation SHA-256: ${e(report.explanationSha256)}</p><p>ConsentLens does not verify the original document, reviewer identity, or legal compliance. This report is editable and is not a digital signature.</p><p>To save a PDF, open your browser’s Print menu and choose Save as PDF.</p></footer></body></html>`;}
export function downloadBlob(content:string,name:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
